### ISSUE TITLE
Issues with Messages

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#1626]
Encountered the following problems the first time I tried to use the message UI (I didn't go looking for these problems, I just hit them trying to create the video)

# Items I would call critical
1) Close button deletes all entered information about message and just closes window without notification.  It took several minutes for me to realize I hadn't hit save.   This alone makes the new "user friendly messages" actually less user friendly.

    > -- Changed close text to "Close without saving" and preventing closing the modal by clicking outside of it

1) When an invalid json schema is provided, you get the following error message and lose all of your work:
![image](https://github.com/sartography/spiff-arena/assets/515662/9ce4d959-22d4-4aeb-bb90-ae65c8c4ba77) You have to start all over again. 

    > -- Added rsjf validation to make sure it is valid json

1) Frequent errors about "message_name" must be a string, when it is clearly a string - maybe it doesn't like underscores? 
![image](https://github.com/sartography/spiff-arena/assets/515662/002810fa-fedd-4c18-81f4-ec3a09574734)

    > -- Cannot repro but I did add pattern and validation message to make sure its a valid format - did same with Location

1) Dropdown does not populate with an option after creating a message  - at least not always.  The first message required a hard refresh.  Perhaps it refreshes if you click off and back on again - but very disorienting - I thought I'd failed to click save again.

    > -- Fixed with https://github.com/sartography/spiff-arena/commit/c9df8bec8bd268e15ea89909e70f2d239ce1c214

1) On running for the first time, I get this error message:
![image](https://github.com/sartography/spiff-arena/assets/515662/7ab731c8-ba49-424e-9ff1-428376517f4c)

    > -- Fixed in SpiffWorkflow

1) A missing payload in a send message fails with the following error that does not provide an explanation
![image](https://github.com/sartography/spiff-arena/assets/515662/d98f9647-9fd5-47b8-8b65-0d2e56370da4)

    > -- This bug exists in the current system - recommend deferring it

1) Correlation keys seem to be getting set under the message name or under some default "Main Correlation Key" heading that is causing the return message to fail.  I don't know what the thought process behind this is - maybe we can talk about it tomorrow.
![image](https://github.com/sartography/spiff-arena/assets/515662/13f47d81-c069-45fb-943a-725ffa92613c)

    > -- Fixed with new bpmn-js-spiffworkflow

# Dreams of a better future that I don't expect to see fixed in this ticket

1) Any way we could have even a basic json editor for the schema?
1) The ability to save and reuse a schema comes up for me frequently in trying to build these examples.  I'd love to re-use the schema for the form, the send, and the receive messages.  Having all these connected would make it far easier to explain to people.

**Comment by madhurrya** [comment]
9. Even if I save the data, when I click on the Message editor again Json schema and Message Name is empty. Whether I use the Close button or the x to close or even if I click outside the popup same happens.
![image](https://github.com/sartography/spiff-arena/assets/110527567/2762b162-a192-4572-b738-1f11fad35f20)

After opening the Message Editor again
![image](https://github.com/sartography/spiff-arena/assets/110527567/b21cd71e-ca85-41d5-820a-d921e057b23c)

**Comment by madhurrya** [comment]
10. I added a matching condition and saved it.
![image](https://github.com/sartography/spiff-arena/assets/110527567/fd491c6a-a5c4-4bbd-9da8-95c743af6d69)

But when I open the diagram next time the matching condition is missing.
![image](https://github.com/sartography/spiff-arena/assets/110527567/23ed4de3-02ec-4c82-893d-7915f94711d6)

**Comment by madhurrya** [comment]
11 The text here seems to be getting cut
![image](https://github.com/sartography/spiff-arena/assets/110527567/e9c1e568-9c12-4bac-8819-5a16448edbe8)

**Comment by jasquat** [comment]
@theaubmov for number 10 above, I'm not having an issue setting the matching condition to true however, if I uncheck it then the xml sets it to "false" but the checkbox is always checked from that point on. The conditional may need to check for strings as well rather than a boolean only.

**Comment by jasquat** [comment]
@madhurrya is number 8 still happening? I cannot reproduce that.

**Comment by madhurrya** [comment]
@jasquat yes it still happens.  https://drive.google.com/file/d/1sEXf22IK5QakN9Na28rnljfNcZ2tnDWi/view?usp=sharing
Please try with a new message

**Comment by jasquat** [comment]
Okay, I think number 8 is mostly fixed although I do think the state does get in an odd state when moving between tabs however this state isn't always reflected within the form. Will have to look more into it.

**Comment by jasquat** [comment]
To sum up the state of this. All issues seem to have been addressed except for issues 5-7. I'm not sure what the best way to handle those errors in 5 and 6 are and I do not fully understand issue 7.

**Comment by madhurrya** [comment]
12. The variable name is still missing from the old models


![Image](https://github.com/sartography/spiff-arena/assets/110527567/8c2e19a3-07ea-40c0-a7f7-be513cfd0b94)

**Comment by madhurrya** [comment]
13. It might be better to move the Save button before the Close button and move the close button to the right a bit


![Image](https://github.com/sartography/spiff-arena/assets/110527567/3ab9a96f-8018-4620-ba30-fc10f0de2b7f)

**Comment by madhurrya** [comment]
14. If I define the payload in the Prescript of the Send task, it doesn't recognize it. But if I define it in a script task before that then it works. Is that the expected behaviour?


![Image](https://github.com/sartography/spiff-arena/assets/110527567/00512ec8-ab74-41c2-a2cc-f73a08259930)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/92c9f447-aca3-46b7-82fe-2ea718d2ef6b)

**Comment by madhurrya** [comment]
15. When I try to add a matching condition it says 'No matching conditions can be established since the selected message has no correlation properties'. But it has a correlation property.

Model : https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing:simple-receive-message/files/simple-receive-message.bpmn

![Image](https://github.com/sartography/spiff-arena/assets/110527567/800e5df4-bc7d-4ad6-ab79-5d884774380f)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/8f01c21c-0848-4d47-94b1-f21921d1376a)

**Comment by madhurrya** [comment]
16. It seems I can't create any new messages in new models, as I keep getting this error 

![Image](https://github.com/sartography/spiff-arena/assets/110527567/41788e29-750b-4b93-a296-4307fdb7c0ef)

**Comment by jasquat** [comment]
For issue:
12 - @theaubmov - is this an issue with bpmn-js-spiiffworkflow. It looks like the variable names used to be in a different place where it was on the message itself and now it's on a definition. Can it look into both and move appropriately?
13 - yep agreed. there are other changes we want to do with this editor and we can look into at that time.
14 - that is a good question. @essweine do you know if something like that works in SpiffWorkflow?
15 - @theaubmov bpmn-js-spiffowrkflow issue?
16 - @madhurrya  if you get it again let us know
17 - I can't see the error since i do not have access to the screenshot and it's pixelated in its current form.

Also, the message improvements branch has been merged to main now so maybe let's create new tickets for new issues instead of using this one. After these last few are addressed we should close this ticket.

**Comment by madhurrya** [comment]
@jasquat I updated the message for 17. As I can remember I got the same error in 16. I think after that I keep getting the same error when I try to add a new message. If you try to save a new message, you might also get the same error. I can't do anything due to this error.

**Comment by madhurrya** [comment]
As per Jasosn's comment above, created this new ticket for new issues https://github.com/sartography/spiff-arena/issues/1716

**Comment by theaubmov** [comment]
@jasquat @madhurrya In issue 15, the correlation properties are present in the process group, but the process XML is not updated. This is the reason why the XML does not have any correlation properties, which explains why the matching conditions show nothing. The issue can be resolved by opening the message editor and clicking on "save," which will update the XML with new values. Also we consider If the XML and group values are not synchronized with xml, we can consider displaying a message in the message editor to inform the user to click "save" again.

**Comment by madhurrya** [comment]
@theaubmov I tried by saving again and then it was able to add the Matching condition. But when I saved the model and came back, then again it is missing.
![image](https://github.com/sartography/spiff-arena/assets/110527567/03d17532-c11a-4374-a3cf-1136797ffa0b)

**Comment by madhurrya** [comment]
The last issue I mentioned above is still there. When I come back to a task later and check the matching condition, it shows as no matching condition.
![image](https://github.com/sartography/spiff-arena/assets/110527567/f01f6aac-9ed4-474b-8b1f-5663c857ac8f)

**Comment by madhurrya** [comment]
I am still noticing the issue no. 15 for this model. Even though it has a correlation it doesn't show the option to add the Matching condition. (But for some other models/messages it worked)
https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing4:receive-message/files/receive-message.bpmn

**Comment by madhurrya** [comment]
Issue no 16 is still there. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/a29a857a-ea35-4d7f-8f75-f23e775cfd39)

**Comment by madhurrya** [comment]
Issue No 12 is also not fixed. Still the Variable is missing in old models.

**Comment by jasquat** [comment]
Latest fixes have been deployed to qa5.

**Comment by madhurrya** [comment]
Closing this ticket as most of these issues and fixed and new issues have been added for existing ones.
