### ISSUE TITLE
Reset process here - Go button doesn’t work as expected

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#767]
In this model https://dev.app.spiff.status.im/admin/process-models/misc:test:madhu-model-2

I resetted to manual task 1 and resumed and when clicked Go, it takes me back to the process instance page instead of taking me to that activity.
This seems to happen in several test models I tried.

**Comment by harmeet-status** [comment]
@madhurrya can you retest and see if this is still an issue.

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

I am still noticing this issue.
Checked with another model now. https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-submit-button-text-1

https://dev.app.spiff.status.im/i/16432

Please check this video. After reset and resumed it behaves like this.
https://drive.google.com/file/d/170BpZ-6lo0Kvo7YihDF5-L6U5a8Z6ppo/view?usp=sharing 

And I think there is something wrong with this message also since it is assigned to this use 

![Image](https://github.com/sartography/spiff-arena/assets/104047049/859aa4a6-2e8e-435a-8023-c9ddaaf8d5d1)

**Comment by danfunk** [comment]
Please retest when the new background processor is in place.

**Comment by dinithihj** [comment]
This issue still exists in dev.mod environment where the new background processor is in place.

Video link -https://drive.google.com/file/d/1nLrftQDNmRgffudXCasOFRuYfeem0P1N/view?usp=sharing

**Comment by jasquat** [comment]
Updated dev.mod with code from dev.app. That should resolve the issue.

**Comment by dinithihj** [comment]
This issue still exists in the dev.mod environment.

Video Link - https://drive.google.com/file/d/1Pt92wSJTyu4nDpIRKl6XBc8cD8w4iEEn/view?usp=sharing

**Comment by burnettk** [comment]
we should consider hammering #811 in the next release after this one, since we now have a script that eliminates duplicate rows.

**Comment by madhurrya** [comment]
This issue is fixed now. Tested in dev.app/test.app

**Comment by madhurrya** [comment]
Released to Prod on 2024 February 20th
