### ISSUE TITLE
Need to display a proper error message for Form Builder ID entry with "/"

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#804]
When entering '/' in the Form Builder ID and saving, the message 'Form Saved It saved' is displayed. However, the JSON file is not created in the Files section. It would be beneficial to show a proper error message when users enter invalid characters as an ID. 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/9526a52a-fbb5-49f4-a6a7-fdc23e9f8749)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/027a7919-8169-4137-9af9-942cb0acaa57)

Currently, it is possible to create files with characters \*?"<>| which are not recommended by operating systems for file names. It would be advisable to restrict these characters in the Form Builder ID as well, as using them can result in issues when trying to download or delete files.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/f71ddab6-158c-4f62-9e1b-543d1f14f983)

**Comment by burnettk** [comment]
addressed by https://github.com/sartography/spiff-arena/pull/915

**Comment by dinithihj** [comment]
Tested on dev.app (version 325/327) and issue still exists. 

When entering '/' in the Form Builder ID and saving, the message 'Form Saved It saved' is displayed. However, the JSON file is not created in the Files section. 
![image](https://github.com/sartography/spiff-arena/assets/123297840/f1c3d45a-1405-419e-a045-93b0406d86b3)
![image](https://github.com/sartography/spiff-arena/assets/123297840/17bfdb49-7663-4a23-89e3-d7a258806716)

**Comment by burnettk** [comment]
@dinithihj i think based on your screenshot that you are somehow accessing the old pre-funk form builder. that isn't great. i guess we need to remove that code. how are you getting there? could you add steps or a video?

**Comment by dinithihj** [comment]
@burnettk I just clicked on the "New JSON file" and on the ID field purposely typed "/".

Video Link https://drive.google.com/file/d/1mS2_nD7P1M6RZguZRfxcOATikTZTWJ_e/view?usp=sharing

Note- When I try to create a file from Properties panel -> JSON Schema Filename -> Launch Editor, that did not allow me to create the file with "/"
![image](https://github.com/sartography/spiff-arena/assets/123297840/47ce7f41-50a1-4cdc-8e97-90d5909cbb26)

![image](https://github.com/sartography/spiff-arena/assets/123297840/1bf1d861-3701-408a-94d2-1334ac2e901d)
